# Generated by Django 5.1.3 on 2024-12-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_about_contact_lease_properties_service_slider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='agents/')),
            ],
        ),
        migrations.CreateModel(
            name='Properties_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties_list/')),
                ('price', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('beds', models.CharField(max_length=50)),
                ('baths', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.CreateModel(
            name='Lease_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.lease')),
            ],
        ),
    ]
