# Generated by Django 5.1.3 on 2024-12-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_agents_properties_list_rename_service_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
