# Generated by Django 5.1.3 on 2024-12-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0004_about_view_services_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
        migrations.DeleteModel(
            name='Services_view',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='property_single',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.service'),
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
