# Generated by Django 5.1.3 on 2024-12-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_service_delete_services_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
