# Generated by Django 5.1.3 on 2024-12-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0006_agents_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
