# Generated by Django 5.1.3 on 2024-12-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0007_rename_agents_agent_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Properties_list',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='location',
        ),
        migrations.AddField(
            model_name='properties',
            name='area',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='properties',
            name='baths',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='properties',
            name='beds',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='country',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.properties'),
        ),
    ]
