# Generated by Django 5.1.3 on 2024-12-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0008_propertyimages_delete_properties_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lease.properties'),
        ),
    ]
