# Generated by Django 5.1.3 on 2024-12-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0009_alter_propertyimages_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='owners/')),
                ('owner_type', models.CharField(default='Real Estate', max_length=40)),
                ('x', models.CharField(max_length=50)),
                ('fb', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('ig', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='properties',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='lease.agent'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='properties',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlord', to='lease.propertyowner'),
        ),
    ]
